project_id = "mpeucejhbaangieynxba"

[functions.setup-admin]
verify_jwt = false

[functions.printful]
verify_jwt = false

[functions.printful-webhook]
verify_jwt = false

[functions.create-printful-order]
verify_jwt = false

[functions.submit-order-to-printful]
verify_jwt = false

[functions.setup-printful-webhooks]
verify_jwt = false
